"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Native navigation is required by the deployed Vinext Worker router. */

import Image from "next/image";
import { useEffect, useRef, useState, type CSSProperties, type KeyboardEvent as ReactKeyboardEvent, type PointerEvent as ReactPointerEvent } from "react";
import AuthButton from "../../../components/AuthButton";
import { courseChapters } from "../../courseData";
import { LessonCelebration } from "../context-rot/LessonCelebration";
import { AiLessonVisualContent, type AiLessonVisual } from "./LessonVisuals";

const lessonId = "basics/ai";
const taskIds = ["identify", "order"];

type ProgressResponse = { user: unknown; lessons?: Record<string, { completedTasks?: string[] }> };

export default function AiLessonClient() {
  const [completedTasks, setCompletedTasks] = useState<string[]>([]);
  const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [openChapter, setOpenChapter] = useState(0);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [visualOpen, setVisualOpen] = useState(false);
  const [activeVisual, setActiveVisual] = useState<AiLessonVisual | null>(null);
  const [celebrationKey, setCelebrationKey] = useState(0);
  const [visualWidth, setVisualWidth] = useState(620);
  const resizing = useRef(false);
  const [sheetHeight, setSheetHeightRaw] = useState(52);
  const [sheetDragging, setSheetDragging] = useState(false);
  const sheetHeightRef = useRef(52);
  const sheetDrag = useRef<{ startY: number; startHeight: number } | null>(null);
  const progress = Math.round((completedTasks.length / taskIds.length) * 100);
  const workspaceStyle = { "--visual-width": `${visualWidth}px`, "--sheet-height": `${sheetHeight}vh`, "--sheet-height-dvh": `${sheetHeight}dvh` } as CSSProperties;

  function setSheetHeight(value: number) { const clamped = Math.min(92, Math.max(14, value)); sheetHeightRef.current = clamped; setSheetHeightRaw(clamped); }

  useEffect(() => {
    const controller = new AbortController();
    fetch("/api/progress", { signal: controller.signal, credentials: "same-origin" })
      .then(async (response) => { if (!response.ok) throw new Error("Progress unavailable"); return response.json() as Promise<ProgressResponse>; })
      .then((data) => { setSignedIn(Boolean(data.user)); setCompletedTasks(data.lessons?.[lessonId]?.completedTasks ?? []); })
      .catch((error: unknown) => { if (!(error instanceof DOMException && error.name === "AbortError")) setSaveStatus("error"); });
    return () => controller.abort();
  }, []);

  useEffect(() => { const phoneLayout = window.matchMedia("(max-width: 920px)"); const frame = window.requestAnimationFrame(() => { if (phoneLayout.matches) setSidebarOpen(false); }); return () => window.cancelAnimationFrame(frame); }, []);

  function startTask(visual: AiLessonVisual) { setActiveVisual(visual); setVisualOpen(true); setSheetHeight(52); }
  function completeTask(task: string) { if (completedTasks.includes(task)) return; const next = [...completedTasks, task]; setCompletedTasks(next); if (signedIn) void saveProgress(next); setVisualOpen(false); setCelebrationKey((key) => key + 1); }
  async function saveProgress(tasks: string[]) { setSaveStatus("saving"); try { const response = await fetch("/api/progress", { method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lessonId, completedTasks: tasks }) }); if (!response.ok) throw new Error("Save failed"); setSaveStatus("saved"); } catch { setSaveStatus("error"); } }
  function beginResize(event: ReactPointerEvent<HTMLDivElement>) { resizing.current = true; event.currentTarget.setPointerCapture(event.pointerId); }
  function resizeVisual(event: ReactPointerEvent<HTMLDivElement>) { if (resizing.current) setVisualWidth(Math.min(860, Math.max(380, window.innerWidth - event.clientX))); }
  function endResize(event: ReactPointerEvent<HTMLDivElement>) { resizing.current = false; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); }
  function resizeWithKeyboard(event: ReactKeyboardEvent<HTMLDivElement>) { if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return; event.preventDefault(); setVisualWidth((width) => Math.min(860, Math.max(380, width + (event.key === "ArrowLeft" ? 30 : -30)))); }
  function beginSheetDrag(event: ReactPointerEvent<HTMLDivElement>) { if ((event.target as HTMLElement).closest(".close-visual")) return; sheetDrag.current = { startY: event.clientY, startHeight: sheetHeightRef.current }; setSheetDragging(true); event.currentTarget.setPointerCapture(event.pointerId); }
  function dragSheet(event: ReactPointerEvent<HTMLDivElement>) { if (!sheetDrag.current) return; setSheetHeight(sheetDrag.current.startHeight + ((sheetDrag.current.startY - event.clientY) / window.innerHeight) * 100); }
  function endSheetDrag(event: ReactPointerEvent<HTMLDivElement>) { if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); const drag = sheetDrag.current; sheetDrag.current = null; setSheetDragging(false); if (!drag) return; const height = sheetHeightRef.current; if (Math.abs(height - drag.startHeight) < 3) { setSheetHeight(drag.startHeight >= 70 ? 52 : 88); return; } if (height < 30) { setSheetHeight(52); setVisualOpen(false); return; } setSheetHeight(height < 70 ? 52 : 88); }
  function resizeSheetWithKeyboard(event: ReactKeyboardEvent<HTMLDivElement>) { if (event.key !== "ArrowUp" && event.key !== "ArrowDown") return; event.preventDefault(); setSheetHeight(event.key === "ArrowUp" ? 88 : 52); }

  return <main className="lesson-page">
    <LessonCelebration trigger={celebrationKey} />
    <header className="lesson-header"><div className="lesson-header-left"><button className="sidebar-toggle" type="button" onClick={() => setSidebarOpen((open) => !open)} aria-expanded={sidebarOpen} aria-controls="course-contents"><span aria-hidden="true">{sidebarOpen ? "×" : "☰"}</span><b>{sidebarOpen ? "Hide contents" : "Show contents"}</b></button><a className="lesson-brand" href="/profile#courses" aria-label="Return to your AI workflow course overview"><Image src="/ai-workflows-icon.png" alt="" width={28} height={28} priority /><b>AI workflow course</b></a></div><div className="lesson-crumb"><span>Chapter 01 · The basics</span><span>/</span><b>AI?</b></div><div className="lesson-account"><div className="lesson-progress"><span><i style={{ width: `${Math.max(4, progress)}%` }} /></span><b>{completedTasks.length} / {taskIds.length} tasks</b></div><AuthButton returnTo="/course/basics/ai" compact /></div></header>
    <div className={`lesson-workspace ${sidebarOpen ? "" : "sidebar-closed"} ${visualOpen ? "" : "visual-closed"}`} style={workspaceStyle}>
      <aside className="course-sidebar" id="course-contents" aria-label="Course contents"><div className="course-side-head"><p>AI workflow course</p><h2>Course contents</h2><div><span style={{ width: `${Math.max(4, progress)}%` }} /><small>{progress}% of this lesson</small></div></div><nav>{courseChapters.map((chapter, chapterIndex) => <div className={`side-chapter ${chapterIndex === 0 ? "current" : ""}`} key={chapter.title}><button onClick={() => setOpenChapter(openChapter === chapterIndex ? -1 : chapterIndex)} aria-expanded={openChapter === chapterIndex}><span>{String(chapterIndex + 1).padStart(2, "0")}</span><b>{chapter.title}</b><i aria-hidden="true">{openChapter === chapterIndex ? "−" : "+"}</i></button>{openChapter === chapterIndex ? <ol>{chapter.lessons.map((lesson, lessonIndex) => <li className={lesson.id === lessonId ? "active" : ""} key={lesson.id}><span>{lesson.id === lessonId ? "●" : "○"}</span><div><small>Lesson {chapterIndex + 1}.{lessonIndex + 1}</small>{lesson.path ? <a href={lesson.path}>{lesson.title}</a> : <b>{lesson.title}</b>}</div>{!lesson.path ? <i>LOCKED</i> : null}</li>)}</ol> : null}</div>)}</nav><div className="chapter-project"><span>CHAPTER PROJECT</span><b>Build your project brain</b><p>Unlocks after all five lessons.</p><small>0 / 5 lessons</small></div></aside>
      <article className="lesson-reading"><div className="lesson-reading-inner context-rot-reading ai-intro-reading"><p className={`progress-save-state ${signedIn ? "connected" : ""}`}>{signedIn ? (saveStatus === "saving" ? "Saving progress…" : saveStatus === "error" ? "Your progress could not be saved yet, while the lesson remains open." : "You are signed in, so task progress saves automatically.") : signedIn === false ? "Sign in above when you want this progress saved across devices." : "Your saved progress is being checked."}</p><p className="reading-kicker">Lesson 01.1</p><h1>AI?</h1><p className="lesson-lede">AI is the broad name for systems that learn patterns from data. The tools in this course use AI models to produce an answer from what you give them. Some can work with language, images, code and other information, while others are stronger at only part of that work.</p><div className="lesson-rule" />
        <section><p className="reading-kicker">Section 1</p><h2>A helpful assistant, not a magic box.</h2><p>Think of an AI tool as an assistant who can produce a fast first pass from the information you give it. It is useful for writing, research, planning, learning and building software, although it can still make things up, miss a constraint or give an answer that sounds better than it is.</p><p>This is why the course starts with clear instructions and simple checks. You do not need to know how to code to begin, but you do need to stay responsible for what the work is trying to achieve.</p><h3 className="ai-section-heading">Making things is faster, making useful things is still hard.</h3><p>Agentic AI has lowered the threshold for turning an idea into an app, a website or a small tool. People can now create a first version in far less time, but the rise in released apps has not produced the same rise in people using them, as the chart below shows.</p><p>There are many reasons for this. A project can become hard to manage, the idea may be too broad to matter to a particular group of people, or the finished work may not solve a problem well enough. This course focuses on reducing the pain of the first problem, so you can keep ambitious projects understandable when they become large.</p><figure className="ai-created-figure"><Image src="/created-vs-used.png" alt="Chart comparing a rise in mobile apps released with limited growth in how often people use them." width={450} height={528} /><figcaption><b>Making an app is getting faster.</b><p>AI can help create a first version quickly, while people still need to decide what to make, keep the project manageable and check whether it works for someone.</p></figcaption></figure></section>
        <section><p className="reading-kicker">Section 2</p><h2>Most people meet AI in a chat.</h2><p>You can ask one-off questions in tools such as <a className="lesson-reference-link" href="https://chatgpt.com/" target="_blank" rel="noreferrer">ChatGPT</a>, <a className="lesson-reference-link" href="https://claude.ai/" target="_blank" rel="noreferrer">Claude</a> or <a className="lesson-reference-link" href="https://gemini.google.com/" target="_blank" rel="noreferrer">Gemini</a>. This is a good starting point, especially when you want to explore an idea or learn something unfamiliar.</p><p>Different tools can answer the same request differently because they use different models, settings, guardrails and information. Each model has a training range, sometimes ending at a date such as 2024, so it may not know a recent event or a changed fact. Many tools add search to retrieve current sources and reduce that stale information problem, although you should still check the source and the date. Chapter 2 explains how to choose a model for a particular job. For now, the useful distinction is between asking a quick question and keeping a project organised over time.</p><div className={`inline-task context-task ${completedTasks.includes("identify") ? "complete" : ""}`}><div className="task-heading"><span>TASK 01 · MATCH THE SETUPS</span><b>{completedTasks.includes("identify") ? "COMPLETE ✓" : "4 MATCHES"}</b></div><h3>Connect each kind of setup to the right example or description.</h3><p>Open the side view, link all four pairs, then check your choices. The task only completes when all four are correct.</p><button className="start-task-button" type="button" onClick={() => startTask("match")}>Open task<span aria-hidden="true">→</span></button><p className="task-start-note">The matching cards appear in the side view.</p></div></section>
        <section><p className="reading-kicker">Section 3</p><h2>Your project needs a place to live.</h2><p>A project is a folder that holds the files for one piece of work. An IDE, which means integrated development environment, is an app for opening and editing that folder. <a className="lesson-reference-link" href="https://code.visualstudio.com/" target="_blank" rel="noreferrer">Visual Studio Code</a> is a common IDE, and tools such as <a className="lesson-reference-link" href="https://www.cursor.com/" target="_blank" rel="noreferrer">Cursor</a> add an AI chat alongside the files.</p><p>There are also more advanced tools such as OpenCode, Claude Code and Codex. With these, you spend more time giving the agent instructions and less time working in a visual editor. They can still work with your project files, but they are not the place to start if a browser chat is still new to you.</p><div className={`inline-task context-task observation ${completedTasks.includes("order") ? "complete" : ""}`}><div className="task-heading"><span>TASK 02 · ORDER THE SETUPS</span><b>{completedTasks.includes("order") ? "COMPLETE ✓" : "3 CARDS"}</b></div><h3>Put the three setup styles in the order this course introduces them.</h3><p>Start with a web based chat, move to an IDE when you need to work with project files, then explore non IDE agents when the first two feel familiar.</p><button className="start-task-button" type="button" onClick={() => startTask("order")}>Open task<span aria-hidden="true">→</span></button><p className="task-start-note">Drag the cards in the side view, then check the order.</p></div></section>
        {completedTasks.length === taskIds.length ? <section className="lesson-complete-card"><span>LESSON COMPLETE</span><h2>You know where AI work can begin.</h2><p>{signedIn ? "Your account now holds these completed tasks, so you can continue with Context rot on another device." : "Sign in with Google when you want to keep these completed tasks on another device."}</p></section> : null}
      </div></article>
      {/* A focusable ARIA separator supports pointer dragging and keyboard resizing. */}
      {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-noninteractive-tabindex */}
      {visualOpen && activeVisual ? <div className="lesson-resize-handle" role="separator" aria-label="Resize the lesson visual" aria-orientation="vertical" aria-valuemin={380} aria-valuemax={860} aria-valuenow={visualWidth} tabIndex={0} onPointerDown={beginResize} onPointerMove={resizeVisual} onPointerUp={endResize} onPointerCancel={endResize} onKeyDown={resizeWithKeyboard}><span aria-hidden="true">⋮</span></div> : null}
      {visualOpen && activeVisual ? <aside className={`lesson-visual context-visual${sheetDragging ? " sheet-dragging" : ""}`} aria-label="AI setup task visual"><div className="visual-switcher task-visual-header sheet-drag-surface" onPointerDown={beginSheetDrag} onPointerMove={dragSheet} onPointerUp={endSheetDrag} onPointerCancel={endSheetDrag}><div className="sheet-grab-handle" role="slider" aria-label="Resize the task visual sheet" aria-orientation="vertical" aria-valuemin={14} aria-valuemax={92} aria-valuenow={Math.round(sheetHeight)} tabIndex={0} onKeyDown={resizeSheetWithKeyboard}><span aria-hidden="true" /></div><div><span>Side view</span><b>{activeVisual === "match" ? "Match the setups" : "Order the setups"}</b></div><span className="task-visual-context">{activeVisual === "match" ? "Task 01" : "Task 02"}</span><button className="close-visual" type="button" onClick={() => setVisualOpen(false)} aria-label="Close side view">×</button></div><div className="context-visual-stage ai-visual-stage"><AiLessonVisualContent visual={activeVisual} onComplete={() => completeTask(activeVisual === "match" ? "identify" : "order")} /></div></aside> : null}
      {!visualOpen && activeVisual ? <button className="reopen-visual" type="button" onClick={() => setVisualOpen(true)}><span>Resume task visual</span><b>{activeVisual === "match" ? "Match the setups" : "Order the setups"}</b></button> : null}
    </div>
    <nav className="lesson-bottom" aria-label="Lesson navigation"><a className="lesson-home-back" href="/"><span aria-hidden="true">←</span><b>Back to home</b></a><div><span>CHAPTER 01 · THE BASICS</span><b>{completedTasks.length} of {taskIds.length} tasks complete</b></div><a className={`lesson-next ${completedTasks.length < taskIds.length ? "disabled" : ""}`} aria-disabled={completedTasks.length < taskIds.length} href={completedTasks.length === taskIds.length ? "/course/basics/context-rot" : "/course/basics/ai"}>Next lesson <span aria-hidden="true">→</span></a></nav>
  </main>;
}
