"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Native navigation is required by the deployed Vinext Worker router. */

import { useEffect, useState } from "react";
import AuthButton from "../../../components/AuthButton";
import CourseSignInNotice from "../../../components/CourseSignInNotice";
import ExperienceBadge from "../../../components/ExperienceBadge";
import LessonSaveState from "../../../components/LessonSaveState";
import LessonXpCelebration from "../../../components/LessonXpCelebration";
import { PixelArrow, PixelSpark } from "../../../components/PixelIcons";
import { courseChapters, courseIntroLesson } from "../../courseData";

const lessonId = "basics/project-brain";
const taskIds = ["identify", "maintain", "draft"];
const requiredFacts = ["Goal", "Audience", "Constraints", "Current state", "Decisions", "Next action"];
const facts = [...requiredFacts, "Every chat message", "A list of favourite tools"];
type LessonProgress = Record<string, { completedTasks?: string[]; lessonCompletedAt?: number }>;

export default function ProjectBrainLessonClient() {
  const [completedTasks, setCompletedTasks] = useState<string[]>([]);
  const [lessonProgress, setLessonProgress] = useState<LessonProgress>({});
  const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [completionStatus, setCompletionStatus] = useState<"idle" | "saving" | "error">("idle");
  const [lessonCompletedAt, setLessonCompletedAt] = useState<number | null>(null);
  const [celebrationKey, setCelebrationKey] = useState(0);
  const [showSignInNotice, setShowSignInNotice] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [openChapter, setOpenChapter] = useState(0);
  const [selectedFacts, setSelectedFacts] = useState<string[]>([]);
  const [maintenanceChoice, setMaintenanceChoice] = useState<string | null>(null);
  const [draft, setDraft] = useState({ goal: "", audience: "", constraint: "", nextAction: "" });
  const progress = Math.round((completedTasks.length / taskIds.length) * 100);
  const allTasksComplete = taskIds.every((task) => completedTasks.includes(task));
  const lessonComplete = Boolean(lessonCompletedAt);

  useEffect(() => { const controller = new AbortController(); fetch("/api/progress", { credentials: "same-origin", signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error("Progress unavailable"); return response.json() as Promise<{ user: unknown; lessons?: LessonProgress }>; }).then((data) => { setSignedIn(Boolean(data.user)); setLessonProgress(data.lessons ?? {}); setCompletedTasks(data.lessons?.[lessonId]?.completedTasks ?? []); setLessonCompletedAt(data.lessons?.[lessonId]?.lessonCompletedAt ?? null); }).catch(() => setSaveStatus("error")); return () => controller.abort(); }, []);
  useEffect(() => { const phoneLayout = window.matchMedia("(max-width: 920px)"); const frame = window.requestAnimationFrame(() => { if (phoneLayout.matches) setSidebarOpen(false); }); return () => window.cancelAnimationFrame(frame); }, []);

  function lessonIsComplete(id: string) { return Boolean(id === lessonId ? lessonCompletedAt : lessonProgress[id]?.lessonCompletedAt); }
  function chapterIsComplete(chapter: typeof courseChapters[number]) { return chapter.lessons.every((lesson) => lessonIsComplete(lesson.id)); }
  const basicsLessons = courseChapters[0].lessons;
  const basicsDone = basicsLessons.filter((lesson) => lessonIsComplete(lesson.id)).length;
  function toggleFact(fact: string) { setSelectedFacts((current) => current.includes(fact) ? current.filter((item) => item !== fact) : [...current, fact]); }
  function completeTask(task: string) { if (completedTasks.includes(task)) return; const next = [...completedTasks, task]; setCompletedTasks(next); if (signedIn) void saveProgress(next); }
  async function saveProgress(tasks: string[]) { setSaveStatus("saving"); try { const response = await fetch("/api/progress", { method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lessonId, completedTasks: tasks }) }); if (!response.ok) throw new Error("Save failed"); setSaveStatus("saved"); window.dispatchEvent(new Event("progress-changed")); } catch { setSaveStatus("error"); } }
  async function completeLesson() { if (signedIn === false) { setShowSignInNotice(true); return; } if (!signedIn || !allTasksComplete || lessonComplete || completionStatus === "saving") return; setCompletionStatus("saving"); try { const response = await fetch("/api/progress", { method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lessonId, completedTasks, completeLesson: true }) }); if (!response.ok) throw new Error("Completion failed"); const data = await response.json() as { lesson?: { lessonCompletedAt?: number }; newlyCompleted?: boolean }; if (!data.lesson?.lessonCompletedAt) throw new Error("Completion was not saved"); setLessonCompletedAt(data.lesson.lessonCompletedAt); setCompletionStatus("idle"); window.dispatchEvent(new Event("progress-changed")); if (data.newlyCompleted) setCelebrationKey((key) => key + 1); } catch { setCompletionStatus("error"); } }
  const draftReady = Object.values(draft).every((value) => value.trim().length >= 5);

  return <main className="lesson-page"><LessonXpCelebration trigger={celebrationKey} nextLessonHref="/course/basics/files-handovers" /><header className="lesson-header"><div className="lesson-header-left"><button className="sidebar-toggle" type="button" onClick={() => setSidebarOpen((open) => !open)} aria-expanded={sidebarOpen} aria-controls="course-contents"><span aria-hidden="true">{sidebarOpen ? "×" : "☰"}</span><b>{sidebarOpen ? "Hide contents" : "Show contents"}</b></button><a className="lesson-brand" href="/profile#courses" aria-label="Return to your AI school course overview"><PixelSpark className="lesson-brand-star" /><b>AI school</b></a></div><div className="lesson-crumb"><span>Chapter 01 · The basics</span><span>/</span><b>Your project brain</b></div><div className="lesson-account"><div className="lesson-progress"><span><i style={{ width: `${Math.max(4, progress)}%` }} /></span><b>{completedTasks.length} / 3 tasks</b></div><LessonSaveState signedIn={signedIn} status={saveStatus} /><ExperienceBadge compact /><AuthButton returnTo="/course/basics/project-brain" compact /></div></header>
    <div className={`lesson-workspace visual-closed ${sidebarOpen ? "" : "sidebar-closed"}`}><aside className="course-sidebar" id="course-contents" aria-label="Course contents"><div className="course-side-head"><p>AI workflow course</p><h2>Course contents</h2><div><span style={{ width: `${Math.max(4, progress)}%` }} /><small>{progress}% of this lesson</small></div></div><nav><a className={`course-intro-link ${lessonProgress.intro?.lessonCompletedAt ? "complete" : ""}`} href={courseIntroLesson.path}><span>{lessonProgress.intro?.lessonCompletedAt ? "✓" : "○"}</span><div><small>COURSE INTRO</small><b>{courseIntroLesson.title}</b></div>{lessonProgress.intro?.lessonCompletedAt ? <i>COMPLETE</i> : null}</a>{courseChapters.map((chapter, chapterIndex) => { const chapterComplete = chapterIsComplete(chapter); return <div className={`side-chapter ${chapterIndex === 0 ? "current" : ""} ${chapterComplete ? "complete" : ""}`} key={chapter.title}><button onClick={() => setOpenChapter(openChapter === chapterIndex ? -1 : chapterIndex)} aria-expanded={openChapter === chapterIndex}><span>{chapterComplete ? "✓" : String(chapterIndex + 1).padStart(2, "0")}</span><b>{chapter.title}</b><i>{chapterComplete ? "COMPLETE" : openChapter === chapterIndex ? "−" : "+"}</i></button>{openChapter === chapterIndex ? <ol>{chapter.lessons.map((lesson, lessonIndex) => { const done = lessonIsComplete(lesson.id); return <li className={`${lesson.id === lessonId ? "active" : ""} ${done ? "complete" : ""}`} key={lesson.id}><span>{done ? "✓" : lesson.id === lessonId ? "●" : "○"}</span><div><small>Lesson {chapterIndex + 1}.{lessonIndex + 1}</small>{lesson.path ? <a href={lesson.path}>{lesson.title}</a> : <b>{lesson.title}</b>}</div>{done ? <i>COMPLETE</i> : !lesson.path ? <i>LOCKED</i> : null}</li>; })}</ol> : null}</div>; })}</nav><div className="chapter-project"><span>CHAPTER PROJECT</span><b>Build your project brain</b><p>Unlocks after all five lessons.</p><small>{basicsDone} / {basicsLessons.length} lessons</small></div></aside>
      <article className="lesson-reading"><div className="lesson-reading-inner project-brain-reading"><p className="reading-kicker">Lesson 01.3</p><h1>Your project brain.</h1><p className="lesson-lede">In the last lesson you moved the facts that matter out of the chat and into overview.md. This lesson is about what belongs inside that file, what should come back out of it, and how to keep it worth reading once the project starts changing under you.</p><div className="lesson-rule" />
        <section><p className="reading-kicker">Section 1</p><h2>Six questions the file has to answer.</h2><p>A fresh chat cannot ask you what you meant, so the file has to answer the questions it would otherwise have asked: what you are making, who it is for, which limits you need to respect, what exists already, which decisions are settled and what the next useful action is. Anything that does not help answer one of those six is usually taking up space rather than earning it.</p><p>Length is the constraint that keeps the file honest, because a document nobody rereads stops being accurate within a fortnight. Aim for something you can read in a minute and correct in two, rather than a specification you would have to maintain alongside the work itself.</p><div className="project-brain-preview"><header><span>project / overview.md</span><b>PROJECT BRAIN</b></header><dl><div><dt>Goal</dt><dd>A simple study planner for busy learners.</dd></div><div><dt>Audience</dt><dd>People balancing work and evening study.</dd></div><div><dt>Constraint</dt><dd>Works on a phone and stays free to use.</dd></div><div><dt>Next action</dt><dd>Check the first screen with two learners.</dd></div></dl></div><div className={`inline-task ${completedTasks.includes("identify") ? "complete" : ""}`}><div className="task-heading"><span>TASK 01 · PICK THE FACTS</span><b>{completedTasks.includes("identify") ? "COMPLETE ✓" : `${selectedFacts.length} SELECTED`}</b></div><h3>Pick the six that belong, and leave the other two out.</h3><div className="project-brain-options">{facts.map((fact) => <button type="button" className={selectedFacts.includes(fact) ? "selected" : ""} onClick={() => toggleFact(fact)} key={fact}>{selectedFacts.includes(fact) ? "✓ " : ""}{fact}</button>)}</div><button className="task-complete-button" type="button" onClick={() => { if (requiredFacts.every((fact) => selectedFacts.includes(fact)) && selectedFacts.length === requiredFacts.length) completeTask("identify"); }}>Check choices</button></div></section>
        <section><p className="reading-kicker">Section 2</p><h2>Old facts do as much damage as missing ones.</h2><p>A decision you reversed in week two will keep steering the work in week five if the file still records the original one, because a fresh chat has no way of knowing you changed your mind. Update the overview when you settle a decision, discover a limit or finish something worth recording, and take out the lines that have stopped being true.</p><p>The habit itself is small: before you close the chat that taught you something, spend a minute deciding what the file should now say. That minute is the difference between a file that describes your project and a file that describes your project as it was a month ago.</p><div className={`inline-task ${completedTasks.includes("maintain") ? "complete" : ""}`}><div className="task-heading"><span>TASK 02 · KEEP IT USEFUL</span><b>{completedTasks.includes("maintain") ? "COMPLETE ✓" : "ONE ANSWER"}</b></div><h3>Which habit keeps the file worth reading?</h3><div className="answer-list">{[["rewrite", "Rewrite the entire overview after every chat."], ["update", "Update the relevant facts when a decision or current state changes."], ["ignore", "Leave it alone once it has been written."]].map(([value, label]) => <button type="button" className={maintenanceChoice === value ? "selected" : ""} onClick={() => setMaintenanceChoice(value)} key={value}>{label}</button>)}</div><button className="task-complete-button" type="button" onClick={() => { if (maintenanceChoice === "update") completeTask("maintain"); }}>Check answer</button></div></section>
        <section><p className="reading-kicker">Section 3</p><h2>Read your own file the way a stranger would.</h2><p>Open the overview.md you made in the last lesson, or picture a small project you have in mind. Read it as though you had never seen the work before, then answer the four questions below from the file alone. Anything you cannot answer without reaching into your own memory is a gap the next chat would fall into as well.</p><div className={`inline-task build-task ${completedTasks.includes("draft") ? "complete" : ""}`}><div className="task-heading"><span>TASK 03 · CHECK YOUR FILE</span><b>{completedTasks.includes("draft") ? "COMPLETE ✓" : "4 FIELDS"}</b></div><h3>Answer these four from the file, not from memory.</h3><div className="project-brain-form">{([ ["goal", "What does the file say you are making?"], ["audience", "Who does it say the work is for?"], ["constraint", "Which limit does it record?"], ["nextAction", "What does it name as the next action?"] ] as const).map(([field, label]) => <label key={field}>{label}<textarea value={draft[field]} onChange={(event) => setDraft((current) => ({ ...current, [field]: event.target.value }))} rows={2} /></label>)}</div><button className="task-complete-button" type="button" onClick={() => { if (draftReady) completeTask("draft"); }}>Check these answers</button><p className="task-start-note">Your answers remain in this browser and are not saved to your account.</p></div></section>
        {allTasksComplete ? <section className={`lesson-complete-card ${lessonComplete ? "complete" : ""}`}><span>{lessonComplete ? "LESSON COMPLETE" : "READY TO COMPLETE"}</span><h2>{lessonComplete ? "Your file is doing the remembering now." : "Finish the lesson and collect your XP."}</h2><p>{lessonComplete ? "Your account has saved this lesson and its XP. Next you will give the rest of the work the same treatment, so that drafts, research and decisions each have a file of their own." : signedIn ? "All tasks are complete. Confirm the lesson to add 100 XP to your level." : "Sign in with Google to save this lesson and collect its XP."}</p>{lessonComplete ? null : <button className="complete-lesson-button" type="button" disabled={completionStatus === "saving"} onClick={completeLesson}>{completionStatus === "saving" ? "Completing lesson…" : "Complete lesson · +100 XP"}</button>}{completionStatus === "error" ? <small className="completion-error">We could not save the lesson yet. Please try again.</small> : null}</section> : null}</div></article></div>
    <nav className="lesson-bottom" aria-label="Lesson navigation"><a className="lesson-home-back" href="/"><span aria-hidden="true">←</span><b>Back to home</b></a><div><span>CHAPTER 01 · THE BASICS</span><b>{completedTasks.length} of 3 tasks complete</b></div><a className={`lesson-next ${!lessonComplete ? "disabled" : ""} ${signedIn === false && !lessonComplete ? "guest-gate" : ""}`} aria-disabled={!lessonComplete} href={lessonComplete ? "/course/basics/files-handovers" : "/course/basics/project-brain"} onClick={(event) => { if (signedIn === false && !lessonComplete) { event.preventDefault(); setShowSignInNotice(true); } }}>Next lesson <PixelArrow /></a></nav>
    {showSignInNotice ? <CourseSignInNotice returnTo="/course/basics/project-brain" onDismiss={() => setShowSignInNotice(false)} /> : null}
  </main>;
}
